version: "3.8"
services:
  backend:
    build: 
      context: ./myweb
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.23.3
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./story-ui/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    # docker compose -p hoidanit-nginx up -d
